from PySide6.QtCore import Qt, Signal
from PySide6.QtWidgets import QFormLayout, QFrame, QLineEdit, QComboBox, QPushButton, QVBoxLayout, QLabel


class UsersPage(QFrame):
    back_requested = Signal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setObjectName("panel")
        layout = QVBoxLayout(self)
        layout.setContentsMargins(28, 24, 28, 24)
        layout.setSpacing(16)
        title = QLabel("المستخدمون")
        title.setObjectName("pageTitle")
        layout.addWidget(title)
        desc = QLabel("إدارة حسابات مستخدمي البرنامج وتفعيلها وتحديد دور كل مستخدم.")
        desc.setWordWrap(True)
        desc.setObjectName("pageDescription")
        layout.addWidget(desc)
        form = QFormLayout()
        form.setSpacing(12)
        self.username = QLineEdit()
        self.username.setPlaceholderText("اسم المستخدم")
        self.full_name = QLineEdit()
        self.full_name.setPlaceholderText("الاسم الكامل")
        self.password = QLineEdit()
        self.password.setEchoMode(QLineEdit.Password)
        self.password.setPlaceholderText("كلمة المرور")
        self.role = QComboBox()
        self.role.addItems(["مدير النظام", "مدير", "محاسب", "بائع", "مخزن", "مستخدم مخصص"])
        form.addRow("اسم المستخدم", self.username)
        form.addRow("الاسم الكامل", self.full_name)
        form.addRow("كلمة المرور", self.password)
        form.addRow("الدور", self.role)
        layout.addLayout(form)
        buttons = QFrame()
        row = __import__('PySide6.QtWidgets', fromlist=['QHBoxLayout']).QHBoxLayout(buttons)
        for text in ["حفظ المستخدم", "تعديل المستخدم", "تفعيل / إيقاف"]:
            row.addWidget(QPushButton(text))
        layout.addWidget(buttons)
        status = QLabel("قائمة المستخدمين ستظهر هنا عند ربط قاعدة بيانات المستخدمين.")
        status.setWordWrap(True)
        layout.addWidget(status)
        layout.addStretch()
        back = QPushButton("العودة إلى الرئيسية")
        back.setObjectName("secondaryButton")
        back.clicked.connect(self.back_requested.emit)
        layout.addWidget(back, alignment=Qt.AlignLeft)
